### ISSUE TITLE
Dark Mode Flickering When Loading Page

### ISSUE THREAD

**Issue by RianBergen** [RianBergen/RB-Blog-Template#15]
The Page Flickers when dark mode is enabled.

**Comment by RianBergen** [comment]
I am unable to replicate this issue.

**Comment by RianBergen** [comment]
Removing from Project 1.0 due to inability to reproduce. Hopefully, it can be reconfirmed and fixed in the next version.

**Comment by GerritBergen** [comment]
Happens in firefox but not chrome. Will look into this.

**Comment by GerritBergen** [comment]
Possibly fixed in #24

**Comment by RianBergen** [comment]
This is now fixed in Version 1.1.
