### ISSUE TITLE
Suggestions For Version 1.1 Release

### ISSUE THREAD

**Issue by RianBergen** [RianBergen/RB-Blog-Template#16]
Please leave any suggestions in the comments below so that they can be investigated.

**Comment by GerritBergen** [comment]
Some ideas for customization if you're lacking any ;)
These options could go in a settings page in the admin panel, or be in a config file

- Add setting for having main column on left/right side.
- Add setting for disabling sidebar features, such as about/recents/categories/tags/archives
- Add setting for adding a background image
- Add setting for the front page to only show one page, or allow it to show the complete "timeline"
- Add setting to disable comments on a specific page
- Add a link to the github?

**Comment by RianBergen** [comment]
This sounds like stuff for version 2.0. I will move this to that project.

**Comment by RianBergen** [comment]
@GerritBergen Thank you for your suggestions. I have added these individually to the 2.0 Project. This issue is now closed.
