### ISSUE TITLE
Add setting for the front page to only show one page, or allow it to show the complete "timeline"

### ISSUE THREAD

**Issue by RianBergen** [RianBergen/RB-Blog-Template#30]
Add setting for the front page to only show one page, or allow it to show the complete "timeline".

**Comment by RianBergen** [comment]
@GerritBergen Could you clarify what you mean with this?

**Comment by GerritBergen** [comment]
Sure, basically it's an option to have one static post for the front page and a timeline page that shows all posts. And the other option is having just all the posts. (The current system)
