### ISSUE TITLE
Missing release in repo?

### ISSUE THREAD

**Issue by GerritBergen** [RianBergen/RB-Blog-Template#45]
I don't see a published release in the [releases](https://github.com/RianBergen/RB-Blog-Template/releases) page, even though the website points to it in its [update post](https://www.rianbergen.com/post/2020-08-18-website-release-3-0)

**Comment by RianBergen** [comment]
That is correct. This was by accident. I combined version 3.0 and 3.1 as 3.1 was a minor update that just fixes some things.
https://github.com/RianBergen/RB-Blog-Template/releases/tag/3.1
